name: test
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-lambda
      run: |
        python -m pip install --upgrade pip
        pip install cargo-lambda
    
    - name: Tests
      run: |
        cargo test